server:
  port: ${PORT:8888}

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Daniel-Zemanate/PI2G1-back-costume-mania
          timeout: 5
          default-label: ${DEFAULT_LABEL:main}
          force-pull: true
          search-paths: Configuration
          cloneOnStart: true
          skipSslValidation: true
