spring:
  application:
    name: ms-eureka-server
  profiles:
    active: ${PROFILE:default}
  config:
    import: optional:configserver:http://${MS_CONFIG_SERVER_HOST:localhost}:${MS_CONFIG_SERVER_PORT:8888}?fail-fast=true&max-attempts=10&max-interval=3000&multiplier=1.2&initial-interval=1100
