version: "3.8"

volumes:
  vol-costume-mania:
  vol-keycloak-data:
networks:
  net-costume-mania:

services:
  ms-config-server:
    build:
      context: ./ms-config-server/
    container_name: ms-config-server
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "1.0"
          #memory: 512M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_CONFIG_SERVER_DOCKER_PORT
      - DEFAULT_LABEL=$MS_CONFIG_SERVER_DEFAULT_LABEL
    ports:
      - ${MS_CONFIG_SERVER_LOCAL_PORT}:${MS_CONFIG_SERVER_DOCKER_PORT}
    networks:
      - net-costume-mania

  ms-eureka-server:
    build:
      context: ./ms-eureka-server/
      args:
        - PROFILE=$MS_EUREKA_SERVER_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    container_name: ms-eureka-server
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_EUREKA_SERVER_LOCAL_PORT}:${MS_EUREKA_SERVER_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-config-server

  ms-gateway:
    build:
      context: ./ms-gateway/
      args:
        - PROFILE=$MS_GATEWAY_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_GATEWAY_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_GATEWAY_LOCAL_PORT}:${MS_GATEWAY_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-config-server
      - ms-eureka-server

  ms-catalog:
    build:
      context: ./ms-catalog/
      args:
        - PROFILE=$MS_CATALOG_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_CATALOG_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_CATALOG_LOCAL_PORT}:${MS_CATALOG_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway


  ms-delete:
    build:
      context: ./ms-delete/
      args:
        - PROFILE=$MS_DELETE_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_DELETE_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_DELETE_LOCAL_PORT}:${MS_DELETE_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway

  ms-favorite:
    build:
      context: ./ms-favorite/
      args:
        - PROFILE=$MS_FAVORITE_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_FAVORITE_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_FAVORITE_LOCAL_PORT}:${MS_FAVORITE_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway


  ms-product:
    build:
      context: ./ms-product/
      args:
        - PROFILE=$MS_PRODUCT_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_PRODUCT_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_PRODUCT_LOCAL_PORT}:${MS_PRODUCT_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway

  ms-users:
    build:
      context: ./ms-users/
      args:
        - PROFILE=$MS_USERS_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_USERS_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_USERS_LOCAL_PORT}:${MS_USERS_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway


  ms-bills:
    build:
      context: ./ms-bills/
      args:
        - PROFILE=$MS_BILLS_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
    #deploy:
      #resources:
        #limits:
          #cpus: "0.5"
          #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_BILLS_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_BILLS_LOCAL_PORT}:${MS_BILLS_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway


  ms-reporting:
    build:
      context: ./ms-reporting/
      args:
        - PROFILE=$MS_REPORTING_PROFILE
        - MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
        - MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_DOCKER_PORT
    restart: unless-stopped
      #deploy:
      #resources:
      #limits:
      #cpus: "0.5"
    #memory: 256M
    #   Create your personal .env file from .envTemplate
    env_file:
      - ./.env
    environment:
      - PORT=$MS_REPORTING_DOCKER_PORT
      - EUREKA_SERVER_HOST=$MS_EUREKA_SERVER_HOST
      - EUREKA_SERVER_PORT=$MS_EUREKA_SERVER_DOCKER_PORT
    ports:
      - ${MS_REPORTING_LOCAL_PORT}:${MS_REPORTING_DOCKER_PORT}
    networks:
      - net-costume-mania
    depends_on:
      - ms-gateway

