version: "3.8"

services:
  mysqldb:
    image: mysql:8.1
    restart: unless-stopped
#   Create your personal .env file from .envTemplate
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    logging:
      driver: none
    volumes:
      - ./db/script-disfraces.sql:/docker-entrypoint-initdb.d/script.sql