# Use 1openjdk17
# FROM adoptopenjdk/openjdk17:alpine
# FROM openjdk:17-jdk-alpine
FROM registry.access.redhat.com/ubi8/openjdk-17:1.17-4

ARG PROFILE
ARG MS_CONFIG_SERVER_HOST
ARG MS_CONFIG_SERVER_PORT
ENV PROFILE=$PROFILE
ENV MS_CONFIG_SERVER_HOST=$MS_CONFIG_SERVER_HOST
ENV MS_CONFIG_SERVER_PORT=$MS_CONFIG_SERVER_PORT
# Add .jar file generated during compilation
COPY target/ms-eureka-server-0.0.1-SNAPSHOT.jar /app/ms-eureka-server.jar

# Working directory
WORKDIR /app

# Exec command to run the app
#CMD ["java", "-jar", "ms-eureka-server.jar", "--spring.profiles.active=$PROFILE", "--spring.config.import=$MS_CONFIG_SERVER_HOST"]
ENTRYPOINT java -Xmx128m -jar ./ms-eureka-server.jar