spring:
  cloud:
    config:
      enabled: false
  application:
    name: ms-reporting
  datasource:
    url: jdbc:mysql://localhost:3306/costumemania
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    enabled: true

server:
  port: 8086