# Use 1openjdk17
# FROM adoptopenjdk/openjdk17:alpine
# FROM openjdk:17-jdk-alpine
FROM registry.access.redhat.com/ubi8/openjdk-17:1.17-4

# Add .jar file generated during compilation
COPY target/ms-config-server-0.0.1-SNAPSHOT.jar /app/ms-config-server.jar

# Working directory
WORKDIR /app

# Exec command to run the app
#CMD ["java", "-jar", "ms-config-server.jar"]
ENTRYPOINT java -Xmx128m -jar ./ms-config-server.jar