server:
  port: ${port:0}

spring:
  application:
    name: ms-bills
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: #${MYSQL_PASSWORD}
    url: #${MYSQL_URL}
    username: #${MYSQL_USERNAME}
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: false



message: hello from facturacion-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
#