server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-eureka-server
  profiles:
    active: ${PROFILE:default}
#  ------ cloud parameters to exclude if local test is needed ------
#  cloud:
#    config:
#      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/