server:
  port: ${PORT:8761}

spring:
  application:
    name: ms-eureka-server
#  ------ cloud parameters to exclude if local test is needed ------
#  cloud:
#    config:
#      enabled: false
eureka:
  instance:
    hostname: ${EUREKA_SERVER_HOST:localhost}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/