server:
  port: ${port:0}

spring:
  application:
    name: ms-favorite
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ekn31
    url: jdbc:mysql://localhost:3306/costumemania
    username: root
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: false



message: hello from favorite-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
#
