server:
  port: ${port:0}

spring:
  application:
    name: ms-facturacion-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: #
    url: jdbc:mysql://localhost:3306/costumemania
    username: #root
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: false



message: hello from facturacion-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
#
