server:
  port: ${PORT:8090}

spring:
  #  ------ cloud parameters to exclude if local test is needed ------
  cloud:
#    config:
#      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/users/**

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway