server:
  port: ${PORT:8090}

spring:
  #  ------ cloud parameters to exclude if local test is needed ------
  cloud:
#    config:
#      enabled: false
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          ms-gateway:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8180}/realms/${KEYCLOAK_REALM:realm_costume_mania}
        registration:
          ms-gateway:
            scope: openid
            provider: ms-gateway
            client-id: client_gateway_costume_mania #TODO: check if variable is needed
            client-secret: ${GATEWAY_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: 'http://${KEYCLOAK_REDIRECT_HOST:localhost}:${KEYCLOAK_REDIRECT_PORT:8180}/login/oauth2/code/keycloak'

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway