server:
  port: ${PORT:0}

spring:
  application:
    name: ms-product
  datasource:
    driverClassName: ${DDBB_USERNAME:com.mysql.cj.jdbc.Driver}
    url: ${DDBB_URL}
    username: ${DDBB_USERNAME}
    password: ${DDBB_PASSWORD}
    jpa:
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: ${DDBB_DIALECT:org.hibernate.dialect.MySQL8Dialect}
          format_sql: true
      defer-datasource-initialization: true

message: hello from ms-product

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/