server:
  port: ${PORT:0}

spring:
  #  ------ cloud parameters to exclude if local test is needed ------
  #  cloud:
  #    config:
  #      enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_SERVICE:costumemania}
    username: ${DB_USER:costumemania}
    password: ${DB_PASS:123456}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true

message: hello from ms-reporting

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/