server:
  port: ${PORT:0}
  servlet:
    context-path: /api/v1

spring:
  #  ------ cloud parameters to exclude if local test is needed ------
  #  cloud:
  #    config:
  #      enabled: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_SERVICE:costumemania}
    username: ${DB_USER:costumemania}
    password: ${DB_PASS:123456}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

message: hello from ms-users

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/


jwt:
  secret: ${JWT_SECRET}
  expiration: 86480

email:
  sender: ${EMAIL_SENDER}
  password: ${EMAIL_PASSWORD}