# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - Develop

jobs:
  build:

    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Down Docker Compose
      continue-on-error: true
      run: sudo docker compose down

    - name: Clean Docker
      continue-on-error: true
      run: sudo docker system prune -a -f

    - name: Copy .env
      run: |
        cp .env-aws .env

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker Compose
      run: sudo docker compose build

    - name: Run Docker Compose
      run: sudo docker compose -f "docker-compose.yml" up -d